version: "3.2"
services:
  proxy:
    image: "nginx:1.19.5-alpine"
    ports:
      - "${PROJET_PROXY_HTTP_PORT}:80"
    networks:
      - project
    volumes:
      - type: bind
        source: ./teacher/config/nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - front
      - swagger
  front:
    image: "node:14.11.0-alpine3.12"
    networks:
      - project
    volumes:
      - type: bind
        source: "./packages/react-component"
        target: "/app"
    command: /app/run.sh
    working_dir: /app
    environment:
      SUBJECT: "${SUBJECT}"
      WATCH_MOD: "${WATCH_MOD}"
      PROJET_PROXY_HTTP_PORT: "${PROJET_PROXY_HTTP_PORT}"
    dns:
      - 8.8.8.8
  back:
    build: 
      dockerfile: Dockerfile
      context: teacher/docker/back/
    networks:
      - project
    volumes:
      - type: bind
        source: "./packages/express-middleware"
        target: "/app"
      - type: bind
        source: "./subjects/${SUBJECT}/sql"
        target: "/sql"
      - type: bind
        source: "./share"
        target: "/share"
    command: /app/run.sh
    working_dir: /app
    environment:
      BACKEND_PORT: 8080
      SUBJECT: "${SUBJECT}"
      DB_PATH: "/share/db.db"
      WATCH_MOD: "${WATCH_MOD}"
      JWT_SECRET: "qwertyuiopasdfghjklzxcvbnm123456"
    dns:
      - 8.8.8.8
  swagger:
    image: swaggerapi/swagger-ui:v3.37.2
    networks:
      - project
    volumes:
      - type: bind
        source: "./subjects/${SUBJECT}/swagger"
        target: /swagger_spec
    environment:
      - SWAGGER_JSON=/swagger_spec/swagger.yml
      - PORT=80
    
networks:
  project:
    driver: bridge